### ISSUE TITLE
TypeError: unorderable types: str() > int()

### ISSUE THREAD

**Issue by sunil-sangwan** [carpedm20/word2vec-tensorflow#2]
Traceback (most recent call last):
  File "model.py", line 31, in <module>
    w2v.build_vocab(config['corpus'])
  File "/home/shark_s/avishkar/deep /example1/Word2Vec.py", line 32, in build_vocab
    self.counter.extend([list(item) for item in Counter(words).most_common()
  File "/home/shark_s/avishkar/deep /example1/Word2Vec.py", line 33, in <listcomp>
    if item[0] > self.min_frequency])
TypeError: unorderable types: str() > int()

**Comment by gahong00** [comment]
i think it's:
if item[1] > self.min_frequency
